<a href="https://colab.research.google.com/github/SShresth7272/Python-Code/blob/main/Numpy_Practice_Sheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
list_1 = [1, 2, 3, 4, 5]
arr_1d = np.array(list_1)
print(arr_1d)
print(type(arr_1d))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
print(arr_1d.shape)
print(arr_1d.ndim)
print(arr_1d.dtype)
print(arr_1d.size)

(5,)
1
int64
5


In [8]:
import numpy as np

# Create a 3x4 array of zeros (default dtype is float)
zeros_array = np.zeros((3, 4))
print(zeros_array)
zeros_arr = np.zeros((3, 4))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[0, 1])    # Output: 2 (row 0, column 1)
print(arr_2d[:, 1])    # Output: [2, 5, 8] (all rows, column 1)
print(arr_2d[1:3, :2]) # Rows 1&2, first two columns: [[4, 5], [7, 8]]

# Boolean indexing (very powerful!)
arr = np.array([1, 5, 2, 10, 3])
print(arr[arr > 4])    # Output: [5, 10]

2
[2 5 8]
[[4 5]
 [7 8]]
[ 5 10]


Array Indexing and Slicing (CRITICAL):

In [11]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[0, 1])    # Output: 2 (row 0, column 1)
print(arr_2d[:, 1])    # Output: [2, 5, 8] (all rows, column 1)
print(arr_2d[1:3, :2]) # Rows 1&2, first two columns: [[4, 5], [7, 8]]

# Boolean indexing (very powerful!)
arr = np.array([1, 5, 2, 10, 3])
print(arr[arr > 4])    # Output: [5, 10]

2
[2 5 8]
[[4 5]
 [7 8]]
[ 5 10]


Vectorized Operations (The Power of NumPy):

In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a * b)
print(a ** 2)
print(np.sqrt(a))

[5 7 9]
[ 4 10 18]
[1 4 9]
[1.         1.41421356 1.73205081]


In [13]:
arr = np.array([-1, 0.5, 2.7])
print(np.abs(arr))   # Absolute value
print(np.sin(arr))   # Sine
print(np.exp(arr))   # Exponential
print(np.log(arr+2)) # Natural log (avoid log(0))

[1.  0.5 2.7]
[-0.84147098  0.47942554  0.42737988]
[ 0.36787944  1.64872127 14.87973172]
[0.         0.91629073 1.54756251]
