<a href="https://colab.research.google.com/github/SShresth7272/Python-Code/blob/main/Numpy_Practice_Sheet3a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



```
# This is formatted as code
```Creating a DataFrame and Accessing its NumPy Core:

Exercise: Create a DataFrame and convert it to a NumPy array.



In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4.1, 5.2, 6.3],
    'C': ['X', 'Y', 'Z']
})
print(df)
array_old = df.values
print(array_old, array_old.dtype)
array_new = df[['A', 'B']].to_numpy()
print(array_new, array_new.dtype)

   A    B  C
0  1  4.1  X
1  2  5.2  Y
2  3  6.3  Z
[[1 4.1 'X']
 [2 5.2 'Y']
 [3 6.3 'Z']] object
[[1.  4.1]
 [2.  5.2]
 [3.  6.3]] float64


In [ ]:
# Create a 10x3 array of random sales data
import pandas as pd
import numpy as np
sales_data = np.random.randn(10, 3) * 100 + 500  # Mean ~500, Std Dev ~100
df_sales = pd.DataFrame(sales_data, columns=['Product_A', 'Product_B', 'Product_C'])
print(df_sales.head())

    Product_A   Product_B   Product_C
0  604.202259  394.814445  566.057260
1  658.760356  515.389710  450.155977
2  594.401460  374.818104  735.443440
3  611.216478  551.341463  383.367073
4  681.860279  368.872278  540.477867


In [ ]:
product_a_sales = df_sales['Product_A']
print("Mean:", np.mean(product_a_sales))
print("Standard Deviation:", np.std(product_a_sales))
print("Log-Transformed Sales:\n", np.log(product_a_sales))

Mean: 568.2484731729855
Standard Deviation: 87.31621180884306
Log-Transformed Sales:
 0    6.403909
1    6.490360
2    6.387555
3    6.415451
4    6.524825
5    6.192625
6    6.403379
7    6.333442
8    5.907835
9    6.230547
Name: Product_A, dtype: float64


In [ ]:
# On our sales_data array from before
print("Column means:", np.mean(sales_data, axis=0))   # Like df.mean()
print("Row sums:", np.sum(sales_data, axis=1))       # Like df.sum(axis=1)
print("Overall max:", np.max(sales_data))            # Global maximum

Column means: [568.24847317 462.16746959 505.34304244]
Row sums: [1565.07396384 1624.30604283 1704.66300419 1545.92501373 1591.21042329
 1548.13230735 1445.85864218 1405.19963282 1566.47719698 1360.74362479]
Overall max: 735.4434402020742


 Handling Missing Data (np.nan):

Exercise: NumPy uses np.nan to represent missing numerical data. Learn to handle it.

In [ ]:
arr_with_nan = np.array([1, 2, np.nan, 4, 5])
print(np.sum(arr_with_nan))
print(np.nansum(arr_with_nan))
print(np.isnan(arr_with_nan))
# Clean the array
cleaned_arr = arr_with_nan[~np.isnan(arr_with_nan)]
print(cleaned_arr)                  6

nan
12.0
[False False  True False False]
[1. 2. 4. 5.]


In [2]:
import numpy as np
import pandas as pd
data = np.random.rand(5, 3) # 5 samples, 3 features
column_means = np.mean(data, axis=0) # Shape: (3,)
mean_centered_data = data - column_means # The mean is "broadcast" across each row
print(np.mean(mean_centered_data, axis=0)) # Should be very close to [0, 0, 0]

[-1.11022302e-17  1.11022302e-17  2.22044605e-17]


In [3]:
arr = np.arange(9) # 1D array [0, 1, 2, ..., 8]
arr_2d = arr.reshape(3, 3) # Reshape to 3x3
arr_t = arr_2d.T   # Transpose: rows become columns
print("Original shape:", arr.shape)
print("Reshaped:\n", arr_2d)
print("Transposed:\n", arr_t)


Original shape: (9,)
Reshaped:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Transposed:
 [[0 3 6]
 [1 4 7]
 [2 5 8]]
